package test;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;
import annimations.*;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

public class loginController implements Initializable{
	@FXML
	private TextField txtUsername;
	@FXML
	private PasswordField txtPassword;
	@FXML
	private Text lblWelcome;
	@FXML
	private Text lblUserLogin;
	@FXML
	private Text lblUsername;
	@FXML
	private Text lblPassword;
	@FXML
	private Button btnLogin;
	@FXML
	private Text lblRudyCom;
	@FXML
	private Label lblClose;

	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void aksiLogin(ActionEvent event)  {
		// TODO Autogenerated
	}
	
	
	 @Override
	    public void initialize(URL location, ResourceBundle resources) {
	        Platform.runLater(() -> {
	            new FadeInRightTransition(lblUserLogin).play();
	            new FadeInLeftTransition(lblWelcome).play();
	            new FadeInLeftTransition1(lblPassword).play();
	            new FadeInLeftTransition1(lblUsername).play();
	            new FadeInLeftTransition1(txtUsername).play();
	            new FadeInLeftTransition1(txtPassword).play();
	            new FadeInRightTransition(btnLogin).play();

	            lblClose.setOnMouseClicked((MouseEvent event) -> Platform.exit());
	        });

	    }
}
